name: Bug report / 缺陷反馈
description: Report something that isn't working / 报告一个问题
title: "[Bug/缺陷]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug. Please fill out the fields below.
        感谢反馈缺陷，请尽量完整填写以下信息。
  - type: textarea
    id: summary
    attributes:
      label: Summary / 摘要
      description: What happened? / 发生了什么？
      placeholder: A clear and concise description of the bug. / 请简要描述问题。
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce / 复现步骤
      description: How can we reproduce the issue? / 如何复现？
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior / 期望结果
      placeholder: What did you expect to happen? / 你期望发生什么？
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment / 环境信息
      description: OS, runtime version, etc. / 操作系统、运行时版本等。
      placeholder: |
        - OS:
        - Version:
        - Other:
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Logs / screenshots / 日志或截图
      description: Paste relevant logs or attach screenshots (remove secrets). / 粘贴日志或附上截图（注意去除敏感信息）。
      render: shell
    validations:
      required: false
